apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-launchpad
  labels:
    app: devops-launchpad
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: devops-launchpad.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-launchpad
                port:
                  number: 5000
